spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  banner:
    location: classpath:logo-app
    charset: UTF-8
  application:
    name: Words Application
  profiles:
    active: default
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console